### ISSUE TITLE
Cannot build examples on windows

### ISSUE THREAD

**Issue by PhilAndrew** [PurpleKingdomGames/indigo#35]
Error messages attached, why is this?

```
C:\home\projects\indigo\examples>scala -version
Scala code runner version 2.13.3 -- Copyright 2002-2020, LAMP/EPFL and Lightbend, Inc.

C:\home\projects\indigo\examples>java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```

[notbuild.txt](https://github.com/PurpleKingdomGames/indigo/files/4930172/notbuild.txt)

Also I note the path where indigo sbt depenency is located is at

```
C:\home\projects\indigo\examples>dir C:\Users\philip\.ivy2\local\io.indigoengine\sbt-indigo\scala_2.12\sbt_1.0\0.1.1-SNAPSHOT\jars
 Volume in drive C has no label.
 Volume Serial Number is B6A2-54F4

 Directory of C:\Users\philip\.ivy2\local\io.indigoengine\sbt-indigo\scala_2.12\sbt_1.0\0.1.1-SNAPSHOT\jars

16/07/2020  06:02 PM    <DIR>          .
16/07/2020  06:02 PM    <DIR>          ..
16/07/2020  06:32 PM            54,902 sbt-indigo.jar
16/07/2020  06:32 PM                32 sbt-indigo.jar.md5
16/07/2020  06:32 PM                40 sbt-indigo.jar.sha1
               3 File(s)         54,974 bytes
               2 Dir(s)  85,815,513,088 bytes free
```

**Comment by davesmith00000** [comment]
Good timing, I was just thinking about this. If I'm jumping to the right conclusion though, this isn't a windows issue.

The examples and demos (of which a new one is coming very soon) are really intended to be used by me during development to see if my current build is breaking anything. So the versions are set to the current local snapshot, not the latest public release.

So if you changed the version in SBT to `0.1.0` you might expect the examples to build because the dependencies can now be resolved.

Unfortunately it's much worse than that! As I'm developing I'm also breaking the API and evolving the demos and examples. So not only are they not pulling in stable dependencies, they also may not work with the current public release!

What to do? It feels like I might need to maintain a separate repo for a version of the examples and demos that use the current public version. But that sounds like hard work. Ideas welcome.

Temporary workaround. Clone the repo, checkout the `0.1.0` tag, and build. Should work for now while I come up with a better solution.

**Comment by PhilAndrew** [comment]
Hi, thanks - so I try that and it says "Generating Indigo Shader Classes..."

`C:\home\projects\indigo\indigo>sbt cleanAll testAllNoCleanJS localPublishNoClean`

java.io.IOException: Cannot run program "glslangValidator": CreateProcess error=2, The system cannot find the file specified

```
[success] Total time: 14 s, completed 16 Jul. 2020, 7:29:49 pm
Generating Indigo Shader Classes...
[info] Compiling 1 Scala source to C:\home\projects\indigo\indigo\facades\js\target\scala-2.13\classes ...
[error] java.io.IOException: Cannot run program "glslangValidator": CreateProcess error=2, The system cannot find the file specified
[error]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
[error]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[error]         at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:75)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:104)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:118)
[error]         at ShaderGen$.makeShader(ShaderGen.scala:46)
[error]         at $b041f5cac576e6c3268a$.$anonfun$indigoPlatforms$4(build.sbt:179)
[error]         at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
[error]         at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:146)
[error]         at sbt.util.Difference.apply(Tracked.scala:323)
[error]         at sbt.util.Difference.apply(Tracked.scala:303)
[error]         at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:142)
[error]         at sbt.util.Difference.apply(Tracked.scala:323)
[error]         at sbt.util.Difference.apply(Tracked.scala:298)
[error]         at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:141)
[error]         at $b041f5cac576e6c3268a$.$anonfun$indigoPlatforms$3(build.sbt:182)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
[error]         at java.base/java.lang.ProcessImpl.create(Native Method)
[error]         at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:478)
[error]         at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
[error]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
[error]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[error]         at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:75)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:104)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:118)
[error]         at ShaderGen$.makeShader(ShaderGen.scala:46)
[error]         at $b041f5cac576e6c3268a$.$anonfun$indigoPlatforms$4(build.sbt:179)
[error]         at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
[error]         at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:146)
[error]         at sbt.util.Difference.apply(Tracked.scala:323)
[error]         at sbt.util.Difference.apply(Tracked.scala:303)
[error]         at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:142)
[error]         at sbt.util.Difference.apply(Tracked.scala:323)
[error]         at sbt.util.Difference.apply(Tracked.scala:298)
[error]         at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:141)
[error]         at $b041f5cac576e6c3268a$.$anonfun$indigoPlatforms$3(build.sbt:182)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (indigoPlatformsJS / Compile / managedSources) java.io.IOException: Cannot run program "glslangValidator": CreateProcess error=2, The system cannot find the file specified
[error] Total time: 2 s, completed 16 Jul. 2020, 7:29:50 pm

C:\home\projects\indigo\indigo>
```

**Comment by PhilAndrew** [comment]
I guess that is glslangValidator.exe, I need to google search and find how to install?

**Comment by PhilAndrew** [comment]
Well I downloaded from https://github.com/KhronosGroup/glslang/releases/tag/master-tot glslangValidator.exe
Added it to the path.

New problem.

```
[info] Main Scala API documentation to C:\home\projects\indigo\indigo\shared\.js\target\scala-2.13\api...
[info] Wrote C:\home\projects\indigo\indigo\shared\.js\target\scala-2.13\shared_sjs1_2.13-0.1.0.pom
[warn] 2 feature warnings; re-run with -feature for details
[error] java.net.URISyntaxException: Illegal character in path at index 53: https://docs.oracle.com/en/java/javase/11/docs/api/C:\Users\philip\scoop\apps\adoptopenjdk-lts-hotspot\current\jmods\java.base/java/io/Serializable.html
[error]         at java.base/java.net.URI$Parser.fail(URI.java:2913)
[error]         at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
[error]         at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3166)
[error]         at java.base/java.net.URI$Parser.parse(URI.java:3114)
[error]         at java.base/java.net.URI.<init>(URI.java:600)
[error]         at scala.tools.nsc.doc.html.HtmlPage.linkToHtml(HtmlPage.scala:145)
[error]         at scala.tools.nsc.doc.html.HtmlPage.toLinksIn$1(HtmlPage.scala:202)
[error]         at scala.tools.nsc.doc.html.HtmlPage.toLinksOut$1(HtmlPage.scala:194)
[error]         at scala.tools.nsc.doc.html.HtmlPage.typeToHtml(HtmlPage.scala:205)
[error]         at scala.tools.nsc.doc.html.HtmlPage.typeToHtml(HtmlPage.scala:182)
[error]         at scala.tools.nsc.doc.html.page.EntityPage.inside$1(Entity.scala:897)
[error]         at scala.tools.nsc.doc.html.page.EntityPage.signature(Entity.scala:906)
[error]         at scala.tools.nsc.doc.html.page.EntityPage.signature$(Entity.scala:799)
[error]         at scala.tools.nsc.doc.html.page.EntityPage$$anon$1.signature(Entity.scala:1033)
[error]         at scala.tools.nsc.doc.html.page.EntityPage.memberToHtml(Entity.scala:378)
[error]         at scala.tools.nsc.doc.html.page.EntityPage.memberToHtml$(Entity.scala:357)
[error]         at scala.tools.nsc.doc.html.page.EntityPage$$anon$1.memberToHtml(Entity.scala:1033)
[error]         at scala.tools.nsc.doc.html.page.EntityPage.$anonfun$memsDiv$1(Entity.scala:355)
[error]         at scala.tools.nsc.doc.html.page.EntityPage.memsDiv(Entity.scala:355)
[error]         at scala.tools.nsc.doc.html.page.EntityPage.memsDiv$(Entity.scala:353)
[error]         at scala.tools.nsc.doc.html.page.EntityPage$$anon$1.memsDiv(Entity.scala:1033)
[error]         at scala.tools.nsc.doc.html.page.EntityPage.$init$(Entity.scala:309)
[error]         at scala.tools.nsc.doc.html.page.EntityPage$$anon$1.<init>(Entity.scala:1033)
[error]         at scala.tools.nsc.doc.html.HtmlFactory.writeTemplate$1(HtmlFactory.scala:167)
[error]         at scala.tools.nsc.doc.html.HtmlFactory.writeTemplates(HtmlFactory.scala:169)
[error]         at scala.tools.nsc.doc.html.HtmlFactory.generate(HtmlFactory.scala:155)
[error]         at scala.tools.nsc.doc.html.Doclet.generateImpl(Doclet.scala:30)
[error]         at scala.tools.nsc.doc.doclet.Generator.generate(Generator.scala:35)
[error]         at scala.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:139)
[error]         at scala.tools.nsc.doc.DocFactory.document(DocFactory.scala:142)
[error]         at xsbt.Runner.run(ScaladocInterface.scala:34)
[error]         at xsbt.ScaladocInterface.run(ScaladocInterface.scala:19)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error]         at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error]         at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:177)
[error]         at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:158)
[error]         at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:39)
[error]         at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:39)
[error]         at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:83)
[error]         at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:76)
[error]         at sbt.RawCompileLike$.$anonfun$cached$3(RawCompileLike.scala:67)
[error]         at sbt.RawCompileLike$.$anonfun$cached$3$adapted(RawCompileLike.scala:65)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:72)
[error]         at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:55)
[error]         at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1635)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (sharedJS / Compile / doc) java.net.URISyntaxException: Illegal character in path at index 53: https://docs.oracle.com/en/java/javase/11/docs/api/C:\Users\philip\scoop\apps\adoptopenjdk-lts-hotspot\current\jmods\java.base/java/io/Serializable.html
[error] Total time: 10 s, completed 16 Jul. 2020, 8:08:51 pm

C:\home\projects\indigo\indigo>
```

**Comment by davesmith00000** [comment]
Quite right about glslangValidator.

This bit is interesting:
`https://docs.oracle.com/en/java/javase/11/docs/api/C:\Users\philip\scoop\apps\adoptopenjdk-lts-hotspot\current\jmods\java.base/java/io/Serializable.html`

Don't suppose you're on windows 10? I understand it has a bash shell these days. If so you could try `bash build.sh` from the repo root in there?

**Comment by PhilAndrew** [comment]
As a workaround, using Ubuntu on Windows https://docs.microsoft.com/en-us/windows/wsl/install-win10

I re-installed java, scala, sbt etc for Ubuntu command line, then also `sudo apt install glslang-tools` 

Then able to successfully `sbt publishLocal for indigo/indigo`

Otherwise when trying to build on windows DOS prompt it fails as described in above discussion. 

My opinion, many game programmers are likely to be on Windows, although I have both Ubuntu and Windows for development, I tend to do my game stuff in Windows, support for windows straight out of the box without effort would be nice to reduce developer friction.

**Comment by davesmith00000** [comment]
Thank you very much for posting the workaround @PhilAndrew.

I agree with your opinion, most of game dev is Windows-centric - it's one of the reasons I made Indigo, to have Windows quite so front and centre. And ~most~ all of the Scala developers I know are Mac or Linux. But you're right, a better Windows experience is a good idea... this does involve me getting a Window's machine however. 😆😬

In other news, I'm pretty sure with the next release I'll publish the examples and demos to a separate repo that tracks the latest public release. At which point hopefully Windows game devs will have few issues since they won't have to build Indigo itself.

**Comment by davesmith00000** [comment]
Following up on this old issue - I've had a go at this myself now.

The problem of not being able to run glslang I will address (I understand the problem now), but in fact on the current code base if you install glslang with scoop (`scoop install glslang`) it won't let you use the validator, but you just get a warning saying "I couldn't validate the shaders" but the build carries on as expected.
